# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
install:
  - "pip install ."
  - "pip install -r requirements-test.txt --use-mirrors"
script: "python tests/test_widgets.py"